### ISSUE TITLE
DeLight Desktop Wallet

### ISSUE THREAD

**Issue by OlegLeonchenkov** [devaultcrypto/DeLight#14]
Hello!
DeLight Desktop Wallet does not connect to the network.
How do I withdraw funds from my wallet?

**Comment by proteanx** [comment]
> Hello! DeLight Desktop Wallet does not connect to the network. How do I withdraw funds from my wallet?

I've just fixed the error preventing the client from connecting to the servers. A new version will be published shortly. Sorry for the delay!
