### ISSUE TITLE
Change PyInstaller bootloader tag

### ISSUE THREAD

**Issue by EchterAgo** [devaultcrypto/DeLight#2]
Here: https://github.com/devaultcrypto/DeLight/blob/master/contrib/build-wine/_build.sh#L205

This makes sure anti virus engines see more different bootloaders and should reduce false positive detections for both Electron-Cash and your fork.

You can put whatever you want there, but keep $GIT_COMMIT_HASH in it.

**Comment by proteanx** [comment]
Thanks. We're just now getting to the wine files, but I went ahead and switched this one out. (https://github.com/devaultcrypto/DeLight/commit/6a966c46ed1b65bd17991f60b5a3e1cc225624b2)
Sorry again for the android crash logs!
